### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by Shadoweee77** [arturjaworski/homebrew-formulae#1]
Hey Artur,
I'd really like to talk to You about Your domain - is there any way we could talk?
Best regards

**Comment by arturjaworski** [comment]
Hello, as it doesn't seem to be related to the repository, please contact me with a private message. Please let me close the ticket.

**Comment by Shadoweee77** [comment]
Hey I really can't find other way - afaik github doesn't include any DM system.
If You have a discord I'd appreciate if You add me: shad#8725

**Comment by Shadoweee77** [comment]
Is there any other way to contact You @arturjaworski ?
